### ISSUE TITLE
プレイヤーの入力を受け取って正誤判定をする

### ISSUE THREAD

**Issue by kkudou23** [kkudou23/agile-EX_scrum#14]
## 受入条件 
- [ ] 1～3以外が入力された場合はエラーメッセージが出力されアプリが終了する
- [ ] 表示されたquizのanswerと同じ数字が入力された場合に正答数が1増えている

## タスク 
- [ ] [Main.java] キーボードから答え(1～3)を受け取る(1～3以外の入力の場合はエラーメッセージを出力してアプリを終了する)
- [ ] [Quiz.java] プレイヤーが入力した答えが正しいかどうかを確認するisCorrectメソッドを作成
- [ ] [Main.java] クイズの答えと入力された数字が等しいか判定し、正解していた場合正答数をカウントする変数に+1する

**Comment by hosokawa3217** [comment]
you can do it!
